CREATE DATABASE IF NOT EXISTS bundle_system
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE bundle_system;

CREATE TABLE IF NOT EXISTS bundles (
  id          CHAR(36)      NOT NULL PRIMARY KEY,
  name        VARCHAR(100)  NOT NULL,
  description VARCHAR(500)  NULL,
  price       DECIMAL(10,2) NOT NULL,
  items       JSON          NOT NULL,
  created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
